# Understanding Faiss

In [1]:
# #Install Packages
# !pip install faiss-cpu
# !pip install sentence-transformers

In [2]:
# import pandas 
import pandas as pd 

In [3]:
df = pd.read_csv("FAISS_text.csv")

In [4]:
df

text category
0      Meditation and yoga can improve mental health   Health
1  Fruits, whole grains and vegetables helps cont...   Health
2  These are the latest fashion trends for this week  Fashion
3  Vibrant color jeans for male are becoming a trend  Fashion
4                 The concert starts at 7 PM tonight    Event
5  Navaratri dandiya program at Expo center in Mu...    Event
6  Exciting vacation destinations for your next trip   Travel
7  Maldives and Srilanka are gaining popularity i...   Travel

In [5]:
# Converting the text to vector using embeddings 

from sentence_transformers import SentenceTransformer

C:\Users\vmr12\mambaforge\envs\chain\Lib\site-packages\sentence_transformers\cross_encoder\CrossEncoder.py:11: TqdmWarning: IProgress not found. Please update jupyter and ipywidgets. See https://ipywidgets.readthedocs.io/en/stable/user_install.html
  from tqdm.autonotebook import tqdm, trange


In [6]:
# Hugging face encoder 
encoder = SentenceTransformer("all-mpnet-base-v2")
vectors = encoder.encode(df.text)

C:\Users\vmr12\mambaforge\envs\chain\Lib\site-packages\huggingface_hub\file_download.py:1132: FutureWarning: `resume_download` is deprecated and will be removed in version 1.0.0. Downloads always resume when possible. If you want to force a new download, use `force_download=True`.
  warnings.warn(


In [7]:
vectors

array([[-0.00247396,  0.03626723, -0.05290459, ..., -0.09152357,
        -0.03970001, -0.04330489],
       [-0.03357268,  0.00980517, -0.03250129, ..., -0.05165466,
         0.02245888, -0.03156181],
       [-0.01865322, -0.04051315, -0.01235386, ...,  0.00610586,
        -0.07179644,  0.02773852],
       ...,
       [-0.00066459,  0.04252128, -0.05645508, ...,  0.01315471,
        -0.03183568, -0.04357662],
       [-0.03317154,  0.03252454, -0.02484838, ...,  0.0117442 ,
         0.05747125,  0.00571021],
       [-0.00166395,  0.00413827, -0.04597083, ...,  0.02008528,
         0.05656242, -0.00161596]], dtype=float32)

In [8]:
vectors.shape

(8, 768)

In [9]:
vectors[0]

array([-2.47396482e-03,  3.62672321e-02, -5.29045947e-02, -2.17348412e-02,
        1.41723417e-02, -1.01600774e-03,  2.23637614e-02,  3.65196504e-02,
        3.80901359e-02,  5.22006955e-03, -3.00865714e-02,  2.05451506e-03,
        1.08502964e-02, -8.49088207e-02, -5.57268830e-03, -6.06597848e-02,
        2.32008472e-03, -1.51409199e-02,  1.20670618e-02,  1.98905114e-02,
       -1.27936322e-02, -2.72811484e-02, -3.31878550e-02,  3.40648065e-03,
        8.41169432e-03, -1.94854941e-02,  4.88132313e-02,  2.24118438e-02,
        4.53467034e-02, -5.90891913e-02, -9.13182199e-02, -1.22330058e-03,
       -4.05045971e-02,  8.67186673e-03,  1.26565271e-06, -1.92451421e-02,
       -3.20659541e-02, -4.08172384e-02,  8.79177526e-02, -1.52632250e-02,
        1.09908646e-02, -4.47976924e-02, -4.74823173e-03,  3.52632105e-02,
        1.31070651e-02,  1.09944092e-02, -3.45761701e-03,  9.12349075e-02,
        5.68809845e-02,  4.82893400e-02, -4.51438315e-03,  3.58451270e-02,
       -2.44210213e-02, -

In [10]:
dim = vectors.shape[1]

In [11]:
dim

768

In [12]:
import faiss
index = faiss.IndexFlatL2(dim)

In [13]:
index


<faiss.swigfaiss_avx2.IndexFlatL2; proxy of <Swig Object of type 'faiss::IndexFlatL2 *' at 0x000001E80209BF00> >

In [14]:
index.add(vectors)

In [15]:
search_query = "An apple a day keeps doctor away"

In [16]:
vec = encoder.encode(search_query)

In [17]:
vec.shape

(768,)

In [18]:
import numpy as np 
svec = np.array(vec).reshape(1,-1)

In [19]:
svec.shape

(1, 768)

In [20]:
index.search(svec, k=2)

(array([[1.3908098, 1.7193404]], dtype=float32), array([[1, 0]], dtype=int64))

In [21]:
dis, I = index.search(svec, k=2)

In [22]:
dis

array([[1.3908098, 1.7193404]], dtype=float32)

In [23]:
I

array([[1, 0]], dtype=int64)

In [24]:
df.loc[I[0]]

text category
1  Fruits, whole grains and vegetables helps cont...   Health
0      Meditation and yoga can improve mental health   Health